### ISSUE TITLE
undefined arrivals

### ISSUE THREAD

**Issue by jugler** [kyle-kelly/MMM-uber#5]
MMM-Uber module is not working anymore, verified my token and location and the logs are showing this:
```
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/home/pi/MagicMirror/modules/MMM-uber/node_helper.js:58:96)
    at self.callback (/home/pi/MagicMirror/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Request.onRequestError (/home/pi/MagicMirror/node_modules/request/request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
```
Module is showing something like 
<img width="143" alt="screen shot 2018-06-15 at 10 16 12 pm" src="https://user-images.githubusercontent.com/11905375/41496003-bada7cfe-70e9-11e8-860d-4ba7ea59ace8.png">

**Comment by jugler** [comment]
Actually was a different issue, uber api is returning this possible uber rides:
```UberXL|Black SUV|UberPool|UberX|Select|Black```
And it seems this module was expecting:
```Possible values: 'POOL', 'uberXL', 'SELECT', 'BLACK', 'SUV', 'ASSIST', 'WAV', 'TAXI'```
 Weird the Uber Api still mentions the old ones as possible values...

Will submit a PR with the changes

**Comment by kyle-kelly** [comment]
Handled [here](https://github.com/kyle-kelly/MMM-uber/commit/de11095db867be7198e502e564b8b14d487ff4f0). Thanks for your help.

**Comment by jugler** [comment]
Awesome! thanks, I love this module!
